# Generated by Django 5.2.12 on 2026-03-16 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TRUE_FALSE', 'True / False'), ('MCQ_MULTI', 'Tick the Box (Multi-Select)'), ('FLASHCARD', 'Flashcard'), ('FILL_IN_BLANKS', 'Fill in the Blanks'), ('STRUCTURED', 'Structured Answer')], max_length=20),
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_notes', to='api.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
